language: python
python:

  - "3.5"

# command to install dependencies
install:
  - pip3 install opencv-python
  - pip3 install -r ./tools/requirements.txt
# command to run tests
script:
  - nosetests -w GeoTag/
  - nosetests -w tests/
